# Generated by Django 4.2.9 on 2026-04-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=160, verbose_name="Nome")),
                (
                    "nome_abreviado",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Nome Abreviado"
                    ),
                ),
                (
                    "npk",
                    models.CharField(blank=True, max_length=40, verbose_name="NPK"),
                ),
                (
                    "variedade",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Variedade"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVO", "Ativo"), ("INATIVO", "Inativo")],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="cadastros.categoria",
                    ),
                ),
                (
                    "custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="cadastros.custo",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
                "unique_together": {("nome", "categoria", "variedade")},
            },
        ),
    ]
