# Generated by Django 4.2.9 on 2026-04-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtor",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produtores",
                to="cadastros.cliente",
            ),
        ),
    ]
