# Generated by Django 4.2.9 on 2026-04-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_alter_produtor_cliente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtor",
            name="cpf",
            field=models.CharField(max_length=14),
        ),
    ]
