from django.urls import path

from .views import (
    CategoriaCreateView,
    CategoriaDeleteView,
    CategoriaListView,
    CategoriaUpdateView,
    ClienteCreateView,
    ClienteDeleteView,
    ClienteListView,
    ClienteUpdateView,
    ContaPagarCreateView,
    ContaPagarDeleteView,
    ContaPagarListView,
    ContaPagarDetailView,
    ContaPagarReportAnaliticoView,
    ContaPagarReportResumoView,
    ContaPagarReportResumidoView,
    ContaPagarUpdateView,
    CotacaoCreateView,
    CotacaoDeleteView,
    CotacaoListView,
    CotacaoUpdateView,
    CulturaCreateView,
    CulturaDeleteView,
    CulturaListView,
    CulturaUpdateView,
    CustoCreateView,
    CustoDeleteView,
    CustoListView,
    CustoUpdateView,
    FaturamentoCreateView,
    FaturamentoDeleteView,
    FaturamentoListView,
    FaturamentoReportAnaliticoView,
    FaturamentoReportResumoView,
    FaturamentoUpdateView,
    FormaPagamentoCreateView,
    FormaPagamentoDeleteView,
    FormaPagamentoListView,
    FormaPagamentoUpdateView,
    FornecedorCreateView,
    FornecedorDeleteView,
    FornecedorListView,
    FornecedorUpdateView,
    LicencaCreateView,
    LicencaDeleteView,
    PerfilUsuarioLicencaCreateView,
    PerfilUsuarioLicencaDeleteView,
    PerfilUsuarioLicencaListView,
    PerfilUsuarioLicencaUpdateView,
    InviteUsuarioLicencaView,
    LicencaListView,
    LicencaUpdateView,
    OperacaoCreateView,
    OperacaoDeleteView,
    OperacaoListView,
    OperacaoUpdateView,
    PedidoCompraCreateView,
    PedidoCompraDeleteView,
    PedidoCompraListView,
    PedidoCompraReportAnaliticoView,
    PedidoCompraReportResumoView,
    PedidoCompraUpdateView,
    PedidoCompraModalDetailView,
    ProdutoCreateView,
    ProdutoDeleteView,
    ProdutoListView,
    ProdutoUpdateView,
    ProdutorCreateView,
    ProdutorDeleteView,
    ProdutorListView,
    ProdutorUpdateView,
    PropriedadeCreateView,
    PropriedadeDeleteView,
    PropriedadeListView,
    PropriedadeUpdateView,
    SafraCreateView,
    SafraDeleteView,
    SafraListView,
    SafraUpdateView,
    UnidadeCreateView,
    UnidadeDeleteView,
    UnidadeListView,
    UnidadeUpdateView,
    cadastros_page,
    compras_page,
    conta_pagar_pagar_lote,
    conta_pagar_estornar_lote,
    contas_selecionadas,
    dashboard,
    financeiro_page,
    landing_page,
    licencas_page,
    produtores_por_cliente,
    pedidos_por_safra_produtor,
    pedido_detalhes_para_faturamento,
)

app_name = 'core'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('dashboard/', dashboard, name='dashboard'),
    path('app/cadastros/', cadastros_page, name='cadastros_page'),
    path('app/compras/', compras_page, name='compras_page'),
    path('app/financeiro/', financeiro_page, name='financeiro_page'),
    path('app/licencas/', licencas_page, name='licencas_page'),

    path('app/safras/', SafraListView.as_view(), name='safra_list'),
    path('app/safras/novo/', SafraCreateView.as_view(), name='safra_create'),
    path('app/safras/<int:pk>/editar/', SafraUpdateView.as_view(), name='safra_update'),
    path('app/safras/<int:pk>/excluir/', SafraDeleteView.as_view(), name='safra_delete'),

    path('app/culturas/', CulturaListView.as_view(), name='cultura_list'),
    path('app/culturas/novo/', CulturaCreateView.as_view(), name='cultura_create'),
    path('app/culturas/<int:pk>/editar/', CulturaUpdateView.as_view(), name='cultura_update'),
    path('app/culturas/<int:pk>/excluir/', CulturaDeleteView.as_view(), name='cultura_delete'),

    path('app/custos/', CustoListView.as_view(), name='custo_list'),
    path('app/custos/novo/', CustoCreateView.as_view(), name='custo_create'),
    path('app/custos/<int:pk>/editar/', CustoUpdateView.as_view(), name='custo_update'),
    path('app/custos/<int:pk>/excluir/', CustoDeleteView.as_view(), name='custo_delete'),

    path('app/categorias/', CategoriaListView.as_view(), name='categoria_list'),
    path('app/categorias/nova/', CategoriaCreateView.as_view(), name='categoria_create'),
    path('app/categorias/<int:pk>/editar/', CategoriaUpdateView.as_view(), name='categoria_update'),
    path('app/categorias/<int:pk>/excluir/', CategoriaDeleteView.as_view(), name='categoria_delete'),

    path('app/unidades/', UnidadeListView.as_view(), name='unidade_list'),
    path('app/unidades/nova/', UnidadeCreateView.as_view(), name='unidade_create'),
    path('app/unidades/<int:pk>/editar/', UnidadeUpdateView.as_view(), name='unidade_update'),
    path('app/unidades/<int:pk>/excluir/', UnidadeDeleteView.as_view(), name='unidade_delete'),

    path('app/formas-pagamento/', FormaPagamentoListView.as_view(), name='forma_pagamento_list'),
    path('app/formas-pagamento/nova/', FormaPagamentoCreateView.as_view(), name='forma_pagamento_create'),
    path('app/formas-pagamento/<int:pk>/editar/', FormaPagamentoUpdateView.as_view(), name='forma_pagamento_update'),
    path('app/formas-pagamento/<int:pk>/excluir/', FormaPagamentoDeleteView.as_view(), name='forma_pagamento_delete'),

    path('app/operacoes/', OperacaoListView.as_view(), name='operacao_list'),
    path('app/operacoes/nova/', OperacaoCreateView.as_view(), name='operacao_create'),
    path('app/operacoes/<int:pk>/editar/', OperacaoUpdateView.as_view(), name='operacao_update'),
    path('app/operacoes/<int:pk>/excluir/', OperacaoDeleteView.as_view(), name='operacao_delete'),

    path('app/clientes/', ClienteListView.as_view(), name='cliente_list'),
    path('app/clientes/novo/', ClienteCreateView.as_view(), name='cliente_create'),
    path('app/clientes/<int:pk>/editar/', ClienteUpdateView.as_view(), name='cliente_update'),
    path('app/clientes/<int:pk>/excluir/', ClienteDeleteView.as_view(), name='cliente_delete'),

    path('app/fornecedores/', FornecedorListView.as_view(), name='fornecedor_list'),
    path('app/fornecedores/novo/', FornecedorCreateView.as_view(), name='fornecedor_create'),
    path('app/fornecedores/<int:pk>/editar/', FornecedorUpdateView.as_view(), name='fornecedor_update'),
    path('app/fornecedores/<int:pk>/excluir/', FornecedorDeleteView.as_view(), name='fornecedor_delete'),

    path('app/produtores/', ProdutorListView.as_view(), name='produtor_list'),
    path('app/produtores/novo/', ProdutorCreateView.as_view(), name='produtor_create'),
    path('app/produtores/<int:pk>/editar/', ProdutorUpdateView.as_view(), name='produtor_update'),
    path('app/produtores/<int:pk>/excluir/', ProdutorDeleteView.as_view(), name='produtor_delete'),

    path('app/propriedades/', PropriedadeListView.as_view(), name='propriedade_list'),
    path('app/propriedades/nova/', PropriedadeCreateView.as_view(), name='propriedade_create'),
    path('app/propriedades/<int:pk>/editar/', PropriedadeUpdateView.as_view(), name='propriedade_update'),
    path('app/propriedades/<int:pk>/excluir/', PropriedadeDeleteView.as_view(), name='propriedade_delete'),

    path('app/produtos/', ProdutoListView.as_view(), name='produto_list'),
    path('app/produtos/novo/', ProdutoCreateView.as_view(), name='produto_create'),
    path('app/produtos/<int:pk>/editar/', ProdutoUpdateView.as_view(), name='produto_update'),
    path('app/produtos/<int:pk>/excluir/', ProdutoDeleteView.as_view(), name='produto_delete'),

    path('app/pedidos/', PedidoCompraListView.as_view(), name='pedido_list'),
    path('app/pedidos/novo/', PedidoCompraCreateView.as_view(), name='pedido_create'),
    path('app/pedidos/<int:pk>/editar/', PedidoCompraUpdateView.as_view(), name='pedido_update'),
    path('app/pedidos/<int:pk>/detalhes/', PedidoCompraModalDetailView.as_view(), name='pedido_detail_modal'),
    path('app/pedidos/<int:pk>/excluir/', PedidoCompraDeleteView.as_view(), name='pedido_delete'),
    path('app/pedidos/relatorios/analitico/', PedidoCompraReportAnaliticoView.as_view(), name='pedido_report_analitico'),
    path('app/pedidos/<int:pk>/relatorios/resumo/', PedidoCompraReportResumoView.as_view(), name='pedido_report_resumo'),

    path('app/pedidos/produtores-por-cliente/', produtores_por_cliente, name='produtores_por_cliente'),

    path('app/faturamentos/pedidos-por-safra-produtor/', pedidos_por_safra_produtor, name='pedidos_por_safra_produtor'),
    path('app/faturamentos/pedido-detalhes/', pedido_detalhes_para_faturamento, name='pedido_detalhes_para_faturamento'),

    path('app/cotacoes/', CotacaoListView.as_view(), name='cotacao_list'),
    path('app/cotacoes/novo/', CotacaoCreateView.as_view(), name='cotacao_create'),
    path('app/cotacoes/<int:pk>/editar/', CotacaoUpdateView.as_view(), name='cotacao_update'),
    path('app/cotacoes/<int:pk>/excluir/', CotacaoDeleteView.as_view(), name='cotacao_delete'),

    path('app/faturamentos/', FaturamentoListView.as_view(), name='faturamento_list'),
    path('app/faturamentos/novo/', FaturamentoCreateView.as_view(), name='faturamento_create'),
    path('app/faturamentos/<int:pk>/editar/', FaturamentoUpdateView.as_view(), name='faturamento_update'),
    path('app/faturamentos/<int:pk>/excluir/', FaturamentoDeleteView.as_view(), name='faturamento_delete'),
    path('app/faturamentos/relatorios/analitico/', FaturamentoReportAnaliticoView.as_view(), name='faturamento_report_analitico'),
    path('app/faturamentos/<int:pk>/relatorios/resumo/', FaturamentoReportResumoView.as_view(), name='faturamento_report_resumo'),

    path('app/contas/', ContaPagarListView.as_view(), name='conta_list'),
    path('app/contas/selecionadas/', contas_selecionadas, name='contas_selecionadas'),
    path('app/contas/pagar-lote/', conta_pagar_pagar_lote, name='conta_pagar_lote'),
    path('app/contas/estornar-lote/', conta_pagar_estornar_lote, name='conta_estornar_lote'),
    path('app/contas/novo/', ContaPagarCreateView.as_view(), name='conta_create'),
    path('app/contas/<int:pk>/editar/', ContaPagarUpdateView.as_view(), name='conta_update'),
    path('app/contas/<int:pk>/detalhes/', ContaPagarDetailView.as_view(), name='conta_detail'),
    path('app/contas/<int:pk>/excluir/', ContaPagarDeleteView.as_view(), name='conta_delete'),
    path('app/contas/relatorios/analitico/', ContaPagarReportAnaliticoView.as_view(), name='conta_report_analitico'),
    path('app/contas/<int:pk>/relatorios/resumo/', ContaPagarReportResumoView.as_view(), name='conta_report_resumo'),
    path('app/contas/relatorios/resumido/', ContaPagarReportResumidoView.as_view(), name='conta_report_resumido'),

    path('app/licencas/crud/', LicencaListView.as_view(), name='licenca_list'),
    path('app/licencas/crud/nova/', LicencaCreateView.as_view(), name='licenca_create'),
    path('app/licencas/crud/<int:pk>/editar/', LicencaUpdateView.as_view(), name='licenca_update'),
    path('app/licencas/crud/<int:pk>/excluir/', LicencaDeleteView.as_view(), name='licenca_delete'),

    path('app/licencas/vinculos/', PerfilUsuarioLicencaListView.as_view(), name='licenca_vinculo_list'),
    path('app/licencas/vinculos/novo/', PerfilUsuarioLicencaCreateView.as_view(), name='licenca_vinculo_create'),
    path('app/licencas/vinculos/convidar/', InviteUsuarioLicencaView.as_view(), name='licenca_vinculo_invite'),
    path('app/licencas/vinculos/<int:pk>/editar/', PerfilUsuarioLicencaUpdateView.as_view(), name='licenca_vinculo_update'),
    path('app/licencas/vinculos/<int:pk>/excluir/', PerfilUsuarioLicencaDeleteView.as_view(), name='licenca_vinculo_delete'),
]



