# Generated by Django 4.2.9 on 2026-04-08 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compras", "0001_initial"),
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faturamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.DateField()),
                ("nota_fiscal", models.CharField(max_length=40, unique=True)),
                ("vencimento", models.DateField()),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faturamentos",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faturamentos",
                        to="cadastros.custo",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faturamentos",
                        to="compras.pedidocompra",
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faturamentos",
                        to="cadastros.produtor",
                    ),
                ),
            ],
            options={
                "ordering": ["-data", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FaturamentoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("produto", models.CharField(max_length=120)),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=14)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_item", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "faturamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="financeiro.faturamento",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.unidade",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContaPagar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.DateField()),
                ("nota_fiscal", models.CharField(max_length=40)),
                ("vencimento", models.DateField()),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=14)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=14)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("pago", models.BooleanField(default=False)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_pagar",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_pagar",
                        to="cadastros.custo",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_pagar",
                        to="compras.pedidocompra",
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_pagar",
                        to="cadastros.produtor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a Pagar",
                "verbose_name_plural": "Contas a Pagar",
                "ordering": ["pago", "vencimento"],
            },
        ),
    ]
