# Generated by Django 4.2.9 on 2026-04-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="licenca",
            options={"ordering": ["cliente__cliente", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="licenca",
            name="fim_vigencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenca",
            name="inicio_vigencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenca",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATIVA", "Ativa"),
                    ("INADIMPLENTE", "Inadimplente"),
                    ("EXPIRADA", "Expirada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="EXPIRADA",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="licenca",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="licenca",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="licenca",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
