# Generated by Django 4.2.9 on 2026-04-10

from django.db import migrations, models


def copy_cliente_fk_to_nome(apps, schema_editor):
    Licenca = apps.get_model('licencas', 'Licenca')
    Cliente = apps.get_model('cadastros', 'Cliente')

    for lic in Licenca.objects.all().only('id', 'cliente_id'):
        nome = ''
        if getattr(lic, 'cliente_id', None):
            c = Cliente.objects.filter(id=lic.cliente_id).only('cliente').first()
            if c:
                nome = c.cliente
        lic.cliente_nome = nome
        lic.save(update_fields=['cliente_nome'])


def noop_reverse(apps, schema_editor):
    # Sem reversao automatica.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0002_alter_licenca_options_licenca_fim_vigencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenca',
            options={'ordering': ['cliente', '-updated_at']},
        ),
        migrations.AddField(
            model_name='licenca',
            name='cliente_nome',
            field=models.CharField(default='', max_length=150, verbose_name='Cliente'),
        ),
        migrations.RunPython(copy_cliente_fk_to_nome, noop_reverse),
        migrations.RemoveField(
            model_name='licenca',
            name='cliente',
        ),
        migrations.RenameField(
            model_name='licenca',
            old_name='cliente_nome',
            new_name='cliente',
        ),
    ]