# Generated by Django 4.2.9 on 2026-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencas", "0003_licenca_cliente_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenca",
            name="stripe_price_id_anual",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="licenca",
            name="stripe_price_id_semestral",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="licenca",
            name="cliente",
            field=models.CharField(max_length=150, verbose_name="Cliente"),
        ),
    ]
