# Generated by Django 4.2.9 on 2026-04-10 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licencas", "0004_stripe_price_ids_periodos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenca",
            name="cep",
            field=models.CharField(blank=True, default="", max_length=9),
        ),
        migrations.AlterField(
            model_name="licenca",
            name="cidade",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="licenca",
            name="endereco",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="licenca",
            name="numero",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="licenca",
            name="uf",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.CreateModel(
            name="PerfilUsuarioLicenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "licenca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="licencas.licenca",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_licenca",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vinculo Usuario-Licenca",
                "verbose_name_plural": "Vinculos Usuario-Licenca",
            },
        ),
    ]
