# Generated by Django 4.2.9 on 2026-04-18 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licencas", "0005_primeiro_acesso_vinculo_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenca",
            name="data_emissao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenca",
            name="data_vencimento_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="licenca",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[("PIX", "Pix"), ("BOLETO", "Boleto")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="licenca",
            name="plano",
            field=models.CharField(
                blank=True,
                choices=[("SEMESTRAL", "Semestral"), ("ANUAL", "Anual")],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="licenca",
            name="valor_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="licenca",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATIVA", "Ativa"),
                    ("AGUARDANDO_CONFIRMACAO", "Aguardando confirmacao"),
                    ("INADIMPLENTE", "Inadimplente"),
                    ("EXPIRADA", "Expirada"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="EXPIRADA",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ConfirmacaoEmailCadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=80, unique=True)),
                ("expira_em", models.DateTimeField()),
                ("usado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmacoes_email",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmacao de Email",
                "verbose_name_plural": "Confirmacoes de Email",
                "ordering": ["-created_at"],
            },
        ),
    ]
