# Generated by Django 4.2.9 on 2026-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencas", "0007_licenca_data_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenca",
            name="asaas_bank_slip_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="licenca",
            name="asaas_customer_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="licenca",
            name="asaas_invoice_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="licenca",
            name="asaas_payment_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="licenca",
            name="asaas_pix_qr_code_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
