# Generated by Django 4.2.9 on 2026-04-08 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.DateField()),
                ("pedido", models.CharField(max_length=40, unique=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=14)),
                ("produto", models.CharField(max_length=120)),
                ("vencimento", models.DateField()),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_compra",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_compra",
                        to="cadastros.custo",
                    ),
                ),
                (
                    "produtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_compra",
                        to="cadastros.produtor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Compra",
                "verbose_name_plural": "Pedidos de Compra",
                "ordering": ["-data", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Planejamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.DateField()),
                ("preco_produto", models.DecimalField(decimal_places=2, max_digits=14)),
                ("vencimento", models.DateField()),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planejamentos",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "custo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planejamentos",
                        to="cadastros.custo",
                    ),
                ),
                (
                    "safra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planejamentos",
                        to="cadastros.safra",
                    ),
                ),
            ],
            options={
                "ordering": ["-data", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlanejamentoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area_ha",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Area HA"
                    ),
                ),
                ("produto", models.CharField(max_length=120)),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=14)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_item", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "custo_ha",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Custo HA",
                    ),
                ),
                (
                    "planejamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="compras.planejamento",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.unidade",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PedidoCompraItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("produto", models.CharField(max_length=120)),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=14)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_item", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "pedido_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="compras.pedidocompra",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.unidade",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CotacaoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.DateField()),
                ("vencimento", models.DateField()),
                ("produto", models.CharField(max_length=120)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotacoes",
                        to="cadastros.fornecedor",
                    ),
                ),
                (
                    "safra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotacoes",
                        to="cadastros.safra",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.unidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotacao de Produto",
                "verbose_name_plural": "Cotacoes de Produtos",
                "ordering": ["-data", "-id"],
            },
        ),
    ]
