# Generated by Django 4.2.9 on 2026-04-10 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_alter_produtor_cpf"),
        ("compras", "0004_alter_pedidocompra_preco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidocompra",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos_compra",
                to="cadastros.fornecedor",
            ),
        ),
    ]
